### ISSUE TITLE
demo: disabling build volume has no effect

### ISSUE THREAD

**Issue by remcoder** [remcoder/gcode-preview#170]
The checkbox doesn't appear to do anything

<img width="326" alt="image" src="https://github.com/remcoder/gcode-preview/assets/461650/528619b0-080c-41a1-ae37-94a6db72d167">

**Comment by sophiedeziel** [comment]
I noticed that the build volume may not be removed/readded properly in between model changes.

I'm not sure exactly where is the root cause, I have not investigated.

The build volume may be removed, but the change is not visible due to another copy of the build volume on the scene.

If you open the dev tools to check how many geometries are on the scene, you'll notice that the number increases each render. For example, change the color of extrusions multiple times.
