### ISSUE TITLE
React demo does not support react-scripts 5

### ISSUE THREAD

**Issue by Nxtmind** [remcoder/gcode-preview#64]
![image](https://github.com/remcoder/gcode-preview/assets/3172111/78bf2b96-826a-4f78-b933-5eea23ea5b5c)

Updating react scripts will lead to errors. 
[package.json#L15](https://github.com/remcoder/gcode-preview/blob/6a853adafa06953952a7134a8a1a67953af76cc7/react-typescript-demo/package.json#L15)
`"react-scripts": "4.0.3"` -> `"react-scripts": "5.0.1"`

Additionally, react-scripts: 4.0.3 does not play nice with node >16 and requires a additional flag in the start script.
`react-scripts --openssl-legacy-provider start`

**Comment by remcoder** [comment]
Hi @Nxtmind! Thanks for reporting this. Unfortunately I have little React knowledge. I gave it a try but I cannot figure out how to fix this. Although error appears the moment the GCodePreview.tsx is loaded. (found out by commenting it out temporarily). 

I googled the error message but it seems to relate to cases where component are declared using class syntax. But all react components in this demo are functions so I don't understand it.

Btw, I did react-scripts 4 to work with Node 18 (which is LTS). Maybe this is of some help to you. I've bumped `.nvmrc` in any case.

I'll leave this open in case anyone, me or anyone else, wants to dig deeper at some point. Any additional insights on this issue is much appreciated.
